export type Material = {
  id: string;
  number: number;
  title: string;
  description: string;
  category: string;
  content: string;
  examples: string[];
  keyPoints: string[];
  quiz: { question: string; options: string[]; correct: number; explanation: string }[];
};

export const MATERIALS: Material[] = [
  {
    id: "mat-01",
    number: 1,
    title: "Pengenalan Teknologi Informasi",
    description: "Memahami konsep dasar TI dan perannya di era digital.",
    category: "Dasar TI",
    content: "Teknologi Informasi (TI) adalah teknologi yang digunakan untuk mengolah, menyimpan, dan menyebarkan informasi. TI mencakup perangkat keras, perangkat lunak, jaringan, dan data. Di era digital, TI menjadi fondasi hampir semua aktivitas: pendidikan, bisnis, komunikasi, dan hiburan.\n\nKomponen utama TI meliputi: input (keyboard, mouse), proses (CPU), output (monitor, printer), dan storage (hard disk, SSD). Dengan memahami TI, kita dapat memanfaatkan teknologi secara efektif dan bertanggung jawab.",
    examples: ["Smartphone sebagai perangkat TI mobile", "Komputer sekolah untuk belajar", "Internet banking"],
    keyPoints: ["TI = mengolah + menyimpan + menyebarkan informasi", "Terdiri dari hardware, software, jaringan, data", "Penting di semua bidang kehidupan"],
    quiz: [{ question: "TI adalah singkatan dari...", options: ["Teknologi Internet", "Teknologi Informasi", "Teknik Informatika", "Transfer Informasi"], correct: 1, explanation: "TI = Teknologi Informasi." }],
  },
  {
    id: "mat-02",
    number: 2,
    title: "Dasar-Dasar Komputer",
    description: "Mengenal bagian-bagian komputer dan cara kerjanya.",
    category: "Dasar TI",
    content: "Komputer adalah mesin elektronik yang dapat menerima data (input), mengolahnya (proses), dan menghasilkan informasi (output). Komputer bekerja berdasarkan arsitektur von Neumann: input → proses → output → storage.\n\nJenis komputer: supercomputer, mainframe, server, desktop, laptop, tablet, smartphone. Setiap jenis memiliki kapasitas dan fungsi berbeda sesuai kebutuhan.",
    examples: ["Desktop PC di lab komputer", "Laptop untuk siswa", "Server sekolah"],
    keyPoints: ["Input → Proses → Output → Storage", "Ada banyak jenis komputer", "CPU adalah otak komputer"],
    quiz: [{ question: "Otak dari komputer disebut...", options: ["RAM", "Hard Disk", "CPU", "Monitor"], correct: 2, explanation: "CPU (Central Processing Unit) adalah otak komputer." }],
  },
  {
    id: "mat-03",
    number: 3,
    title: "Hardware dan Software",
    description: "Perbedaan dan fungsi perangkat keras serta perangkat lunak.",
    category: "Dasar TI",
    content: "Hardware adalah komponen fisik komputer yang bisa dilihat dan disentuh: motherboard, CPU, RAM, hard disk, keyboard, mouse, monitor.\n\nSoftware adalah program/instruksi yang mengendalikan hardware. Software dibagi menjadi: sistem operasi (Windows, Linux), aplikasi (Word, Chrome), dan utility (antivirus).\n\nKeduanya saling membutuhkan: software tidak jalan tanpa hardware, hardware tidak berguna tanpa software.",
    examples: ["Keyboard = hardware", "Microsoft Word = software", "Windows 11 = sistem operasi"],
    keyPoints: ["Hardware = fisik", "Software = program", "Keduanya saling bergantung"],
    quiz: [{ question: "Contoh software adalah...", options: ["Mouse", "Monitor", "Google Chrome", "Keyboard"], correct: 2, explanation: "Google Chrome adalah aplikasi software." }],
  },
  {
    id: "mat-04",
    number: 4,
    title: "Sistem Operasi",
    description: "Mengenal fungsi dan jenis sistem operasi.",
    category: "Dasar TI",
    content: "Sistem Operasi (OS) adalah software yang mengelola seluruh sumber daya komputer dan menjadi penghubung antara user dengan hardware. Tanpa OS, komputer tidak bisa digunakan.\n\nFungsi OS: manajemen proses, memori, file, perangkat I/O, dan keamanan. Contoh OS: Windows, macOS, Linux, Android, iOS.\n\nLinux populer di server karena open source dan stabil. Windows paling umum di desktop.",
    examples: ["Windows 11 di PC", "Android di HP", "Ubuntu di server"],
    keyPoints: ["OS mengelola hardware & software", "Contoh: Windows, Linux, Android", "Tanpa OS komputer tidak bisa dipakai"],
    quiz: [{ question: "Sistem operasi open source yang populer adalah...", options: ["Windows", "macOS", "Linux", "iOS"], correct: 2, explanation: "Linux adalah OS open source." }],
  },
  {
    id: "mat-05",
    number: 5,
    title: "Manajemen File dan Folder",
    description: "Cara mengatur, menyimpan, dan mencari file dengan rapi.",
    category: "Dasar TI",
    content: "File adalah kumpulan data yang disimpan dengan nama dan ekstensi tertentu (.docx, .jpg, .pdf). Folder adalah wadah untuk mengelompokkan file.\n\nPraktik baik: beri nama file yang jelas, buat struktur folder logis (misal: Sekolah/Mapel/Tugas), backup rutin, dan hapus file yang tidak perlu.\n\nShortcut keyboard: Ctrl+C (copy), Ctrl+V (paste), Ctrl+X (cut), Ctrl+Z (undo), F2 (rename).",
    examples: ["Folder 'Tugas_Informatika'", "File 'Laporan_Praktik.pdf'", "Struktur: Drive/Sekolah/2026/"],
    keyPoints: ["Nama file harus jelas", "Struktur folder memudahkan pencarian", "Backup data penting"],
    quiz: [{ question: "Untuk mengganti nama file, tekan tombol...", options: ["F1", "F2", "F5", "Delete"], correct: 1, explanation: "F2 digunakan untuk rename file." }],
  },
  {
    id: "mat-06",
    number: 6,
    title: "Dasar Jaringan Komputer",
    description: "Pengenalan konsep jaringan dan manfaatnya.",
    category: "Jaringan",
    content: "Jaringan komputer adalah kumpulan komputer yang saling terhubung untuk berbagi data dan sumber daya. Manfaat: berbagi file, printer, internet, dan komunikasi.\n\nBerdasarkan jangkauan: PAN (pribadi), LAN (lokal), MAN (kota), WAN (luas/global). Media transmisi: kabel (UTP, fiber) dan nirkabel (WiFi, Bluetooth).\n\nProtokol adalah aturan komunikasi antar perangkat dalam jaringan.",
    examples: ["WiFi sekolah = LAN nirkabel", "Internet = WAN global", "Bluetooth HP = PAN"],
    keyPoints: ["Jaringan = berbagi data & resource", "LAN, MAN, WAN", "Protokol mengatur komunikasi"],
    quiz: [{ question: "Jaringan dalam satu gedung disebut...", options: ["WAN", "MAN", "LAN", "PAN"], correct: 2, explanation: "LAN = Local Area Network." }],
  },
  {
    id: "mat-07",
    number: 7,
    title: "IP Address",
    description: "Memahami alamat unik setiap perangkat di jaringan.",
    category: "Jaringan",
    content: "IP Address adalah identitas unik perangkat dalam jaringan. IPv4 terdiri dari 4 oktet (contoh: 192.168.1.1). IPv6 lebih panjang untuk mengatasi keterbatasan IPv4.\n\nJenis IP: public (bisa diakses internet) dan private (hanya di jaringan lokal). IP bisa statis (tetap) atau dinamis (DHCP).\n\nSubnet mask menentukan bagian network dan host dari IP address.",
    examples: ["192.168.0.1 = IP private router", "8.8.8.8 = DNS Google", "DHCP memberi IP otomatis"],
    keyPoints: ["IP = identitas di jaringan", "IPv4: 4 oktet", "Private vs Public IP"],
    quiz: [{ question: "Contoh IP private adalah...", options: ["8.8.8.8", "192.168.1.1", "1.1.1.1", "208.67.222.222"], correct: 1, explanation: "192.168.x.x adalah rentang IP private." }],
  },
  {
    id: "mat-08",
    number: 8,
    title: "LAN, MAN, dan WAN",
    description: "Perbedaan jangkauan dan karakteristik jaringan.",
    category: "Jaringan",
    content: "LAN (Local Area Network): jangkauan terbatas (ruangan/gedung), kecepatan tinggi, dikelola sendiri. Contoh: jaringan lab sekolah.\n\nMAN (Metropolitan Area Network): jangkauan satu kota, biasanya dikelola ISP atau pemerintah kota.\n\nWAN (Wide Area Network): jangkauan antar kota/negara, menggunakan infrastruktur publik. Internet adalah WAN terbesar di dunia.",
    examples: ["Lab komputer = LAN", "Jaringan antar kampus di satu kota = MAN", "Internet = WAN"],
    keyPoints: ["LAN = lokal", "MAN = kota", "WAN = luas/global"],
    quiz: [{ question: "Internet termasuk jenis jaringan...", options: ["LAN", "MAN", "WAN", "PAN"], correct: 2, explanation: "Internet adalah WAN terbesar." }],
  },
  {
    id: "mat-09",
    number: 9,
    title: "Internet dan Intranet",
    description: "Perbedaan jaringan publik global dan jaringan internal.",
    category: "Jaringan",
    content: "Internet adalah jaringan global publik yang menghubungkan jutaan perangkat di seluruh dunia. Siapa saja bisa mengaksesnya.\n\nIntranet adalah jaringan privat milik organisasi (sekolah, perusahaan) yang hanya bisa diakses anggota internal. Menggunakan teknologi internet (HTTP, TCP/IP) tapi dibatasi aksesnya.\n\nExtranet adalah perpanjangan intranet untuk pihak eksternal tertentu (mitra, vendor).",
    examples: ["Google.com = Internet", "Portal internal sekolah = Intranet", "Sistem vendor perusahaan = Extranet"],
    keyPoints: ["Internet = publik global", "Intranet = privat internal", "Keduanya pakai protokol sama"],
    quiz: [{ question: "Jaringan privat milik organisasi disebut...", options: ["Internet", "Intranet", "Extranet", "Ethernet"], correct: 1, explanation: "Intranet adalah jaringan privat internal." }],
  },
  {
    id: "mat-10",
    number: 10,
    title: "Perangkat Jaringan",
    description: "Router, switch, hub, access point, dan fungsinya.",
    category: "Jaringan",
    content: "Router: menghubungkan jaringan berbeda dan mengarahkan paket data (gateway ke internet).\n\nSwitch: menghubungkan banyak perangkat dalam satu LAN secara cerdas (berdasarkan MAC address).\n\nHub: mirip switch tapi lebih sederhana (broadcast ke semua port) — sudah jarang dipakai.\n\nAccess Point (AP): menyediakan koneksi WiFi. Modem: mengubah sinyal ISP menjadi data digital.",
    examples: ["Router WiFi di rumah", "Switch 24-port di lab", "Access Point di koridor sekolah"],
    keyPoints: ["Router = antar jaringan", "Switch = dalam LAN", "AP = WiFi"],
    quiz: [{ question: "Perangkat yang menghubungkan ke internet adalah...", options: ["Switch", "Hub", "Router", "Repeater"], correct: 2, explanation: "Router menghubungkan jaringan lokal ke internet." }],
  },
];

// Continue materials 11-33
const MORE: Material[] = [
  {
    id: "mat-11", number: 11, title: "Topologi Jaringan",
    description: "Bentuk fisik dan logis hubungan antar perangkat jaringan.",
    category: "Jaringan",
    content: "Topologi jaringan adalah cara perangkat saling terhubung. Topologi fisik: Bus, Star, Ring, Mesh, Tree. Topologi logis menentukan bagaimana data mengalir.\n\nStar paling umum dipakai: semua perangkat terhubung ke switch/hub pusat. Mudah dikelola, jika satu kabel putus tidak mempengaruhi yang lain. Mesh memberikan redundansi tinggi tapi mahal.",
    examples: ["Lab sekolah biasanya Star", "Internet backbone cenderung Mesh", "Token Ring = Ring (klasik)"],
    keyPoints: ["Star paling umum", "Mesh = redundansi tinggi", "Pilih sesuai kebutuhan & budget"],
    quiz: [{ question: "Topologi paling umum di kantor/sekolah adalah...", options: ["Bus", "Ring", "Star", "Mesh"], correct: 2, explanation: "Star mudah dikelola dan andal." }],
  },
  {
    id: "mat-12", number: 12, title: "OSI Layer",
    description: "Model 7 lapisan komunikasi jaringan internasional.",
    category: "Jaringan",
    content: "Model OSI (Open Systems Interconnection) terdiri dari 7 layer: 1 Physical, 2 Data Link, 3 Network, 4 Transport, 5 Session, 6 Presentation, 7 Application.\n\nSetiap layer punya tugas spesifik. Data dikemas (encapsulation) dari layer 7 ke 1 saat dikirim, lalu dibongkar (decapsulation) saat diterima. Memahami OSI membantu troubleshooting jaringan.",
    examples: ["Layer 3 = IP routing", "Layer 4 = TCP/UDP", "Layer 7 = HTTP, FTP"],
    keyPoints: ["7 layer OSI", "Encapsulation & decapsulation", "Berguna untuk troubleshooting"],
    quiz: [{ question: "Layer OSI yang menangani IP address adalah layer...", options: ["1", "2", "3", "4"], correct: 2, explanation: "Network layer (3) menangani routing & IP." }],
  },
  {
    id: "mat-13", number: 13, title: "TCP/IP",
    description: "Protokol inti yang digunakan di internet.",
    category: "Jaringan",
    content: "TCP/IP adalah suite protokol yang menjadi dasar internet. TCP (Transmission Control Protocol) menjamin pengiriman data andal (connection-oriented). IP (Internet Protocol) menangani pengalamatan dan routing.\n\nUDP lebih cepat tapi tidak menjamin (cocok untuk video streaming, game). Model TCP/IP punya 4 layer: Network Access, Internet, Transport, Application.",
    examples: ["HTTP jalan di atas TCP", "DNS sering pakai UDP", "Video call bisa pakai UDP"],
    keyPoints: ["TCP = andal", "UDP = cepat", "Dasar komunikasi internet"],
    quiz: [{ question: "Protokol yang menjamin data sampai dengan benar adalah...", options: ["UDP", "IP", "TCP", "ICMP"], correct: 2, explanation: "TCP connection-oriented dan reliable." }],
  },
  {
    id: "mat-14", number: 14, title: "DNS dan Domain",
    description: "Sistem penamaan yang mengubah nama menjadi IP.",
    category: "Jaringan",
    content: "DNS (Domain Name System) menerjemahkan nama domain (google.com) menjadi IP address. Tanpa DNS, kita harus mengingat angka IP.\n\nHierarki DNS: Root → TLD (.com, .id) → Second-level (google) → Subdomain (www). Proses query: browser → resolver → root → TLD → authoritative server.\n\nDomain didaftarkan melalui registrar (Niagahoster, Google Domains, dll).",
    examples: ["google.com → 142.250.x.x", "DNS publik: 8.8.8.8", "Domain .sch.id untuk sekolah"],
    keyPoints: ["DNS = buku telepon internet", "Domain harus didaftarkan", "8.8.8.8 = DNS Google"],
    quiz: [{ question: "Fungsi DNS adalah...", options: ["Mengamankan data", "Menerjemahkan domain ke IP", "Mempercepat download", "Menghapus virus"], correct: 1, explanation: "DNS mengubah nama domain menjadi IP address." }],
  },
  {
    id: "mat-15", number: 15, title: "Web Browser dan Search Engine",
    description: "Cara kerja browser dan mesin pencari.",
    category: "Web",
    content: "Web browser adalah aplikasi untuk mengakses halaman web (Chrome, Firefox, Edge, Safari). Browser merender HTML, CSS, dan menjalankan JavaScript.\n\nSearch engine (Google, Bing) mengindeks miliaran halaman web dan menampilkan hasil pencarian berdasarkan algoritma relevansi. Tips cari efektif: gunakan kata kunci spesifik, tanda kutip untuk frase exact, operator site: dan -.",
    examples: ["Chrome merender youtube.com", "Cari: site:sch.id informatika", "Gunakan \"tepat seperti ini\" untuk exact match"],
    keyPoints: ["Browser = menampilkan web", "Search engine = mencari informasi", "Gunakan kata kunci efektif"],
    quiz: [{ question: "Contoh web browser adalah...", options: ["Google", "Chrome", "Bing", "Yahoo"], correct: 1, explanation: "Chrome adalah browser; Google adalah search engine." }],
  },
  {
    id: "mat-16", number: 16, title: "Dasar HTML",
    description: "Bahasa markup untuk struktur halaman web.",
    category: "Web",
    content: "HTML (HyperText Markup Language) adalah bahasa standar untuk membuat struktur konten web. HTML menggunakan tag: <h1>, <p>, <a>, <img>, <div>, dll.\n\nDokumen HTML dasar: <!DOCTYPE html>, <html>, <head>, <body>. Tag bisa punya atribut (href, src, class, id). HTML5 menambah semantic tags: <header>, <nav>, <article>, <footer>.",
    examples: ["<h1>Judul</h1>", "<a href='https://...'>Link</a>", "<img src='foto.jpg' alt='deskripsi'>"],
    keyPoints: ["HTML = struktur web", "Tag dibuka dan ditutup", "HTML5 = semantic & modern"],
    quiz: [{ question: "HTML adalah singkatan dari...", options: ["Hyper Text Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyper Transfer Markup Language"], correct: 0, explanation: "HTML = HyperText Markup Language." }],
  },
  {
    id: "mat-17", number: 17, title: "Struktur Dokumen HTML",
    description: "Kerangka standar file HTML yang benar.",
    category: "Web",
    content: "Setiap halaman HTML idealnya memiliki struktur:\n<!DOCTYPE html>\n<html lang=\"id\">\n<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title>Judul Halaman</title>\n</head>\n<body>\n  <!-- konten -->\n</body>\n</html>\n\nHead berisi metadata; body berisi konten yang tampil. Viewport meta penting untuk responsive.",
    examples: ["DOCTYPE menyatakan HTML5", "lang='id' untuk bahasa Indonesia", "viewport untuk mobile-friendly"],
    keyPoints: ["DOCTYPE + html + head + body", "Meta charset & viewport wajib", "Title muncul di tab browser"],
    quiz: [{ question: "Bagian HTML yang menampilkan konten ke user adalah...", options: ["<head>", "<body>", "<meta>", "<title>"], correct: 1, explanation: "Body berisi konten yang terlihat." }],
  },
  {
    id: "mat-18", number: 18, title: "Dasar CSS",
    description: "Memberi gaya dan tampilan pada HTML.",
    category: "Web",
    content: "CSS (Cascading Style Sheets) mengatur tampilan elemen HTML: warna, ukuran, layout, animasi. Cara menulis CSS: inline (style=''), internal (<style>), eksternal (.css file).\n\nSintaks: selector { property: value; }. Contoh: h1 { color: blue; font-size: 24px; }. CSS eksternal paling direkomendasikan untuk maintainability.",
    examples: ["color: red;", "background-color: #000;", "font-family: Arial, sans-serif;"],
    keyPoints: ["CSS = tampilan", "Selector + property + value", "Eksternal lebih rapi"],
    quiz: [{ question: "CSS digunakan untuk...", options: ["Struktur halaman", "Styling tampilan", "Logika program", "Database"], correct: 1, explanation: "CSS mengatur gaya/tampilan." }],
  },
  {
    id: "mat-19", number: 19, title: "Selector dan Property CSS",
    description: "Cara menargetkan elemen dan mengatur propertinya.",
    category: "Web",
    content: "Selector menentukan elemen mana yang di-style: element (p), class (.btn), id (#header), attribute ([type='text']), pseudo (:hover, :focus).\n\nProperty umum: color, background, margin, padding, border, width, height, display, flex, grid. Specificity menentukan mana style yang menang jika bentrok: inline > id > class > element.",
    examples: [".btn-primary { background: black; }", "#logo { width: 48px; }", "a:hover { text-decoration: underline; }"],
    keyPoints: ["Class pakai titik (.)", "ID pakai pagar (#)", "Specificity menentukan prioritas"],
    quiz: [{ question: "Selector untuk class 'card' ditulis...", options: ["#card", ".card", "card", "*card"], correct: 1, explanation: "Class selector diawali titik." }],
  },
  {
    id: "mat-20", number: 20, title: "Responsive Web Design",
    description: "Membuat website nyaman di HP, tablet, dan desktop.",
    category: "Web",
    content: "Responsive Web Design (RWD) membuat layout menyesuaikan ukuran layar. Teknik utama: fluid grid, flexible images, media queries.\n\nMedia query contoh: @media (max-width: 768px) { .menu { display: none; } }. Mobile-first: tulis style mobile dulu, lalu tambah untuk layar lebih besar. Unit relatif (%, rem, vw) lebih fleksibel daripada px tetap.",
    examples: ["@media (max-width: 640px)", "width: 100% pada gambar", "Flexbox/Grid untuk layout adaptif"],
    keyPoints: ["Mobile-first recommended", "Media queries wajib", "Unit relatif lebih fleksibel"],
    quiz: [{ question: "Teknik CSS untuk layout berbeda per ukuran layar disebut...", options: ["Animation", "Media Query", "Transition", "Transform"], correct: 1, explanation: "Media Query mengatur style berdasarkan kondisi layar." }],
  },
];

MATERIALS.push(...MORE);

const MORE2: Material[] = [
  {
    id: "mat-21", number: 21, title: "Dasar JavaScript",
    description: "Bahasa pemrograman untuk interaktivitas web.",
    category: "Pemrograman",
    content: "JavaScript (JS) adalah bahasa pemrograman yang berjalan di browser (dan juga di server dengan Node.js). JS membuat halaman web interaktif: validasi form, animasi, fetch data, dll.\n\nCara menyisipkan: inline (onclick), internal (<script>), eksternal (.js file). JS bersifat dynamic typing dan multi-paradigm (procedural, OOP, functional).",
    examples: ["alert('Halo!')", "document.getElementById('btn')", "console.log('debug')"],
    keyPoints: ["JS = interaktivitas web", "Bisa di browser & server", "Dynamic typing"],
    quiz: [{ question: "Bahasa untuk membuat web interaktif adalah...", options: ["HTML", "CSS", "JavaScript", "SQL"], correct: 2, explanation: "JavaScript menangani perilaku/interaktivitas." }],
  },
  {
    id: "mat-22", number: 22, title: "Variable dan Data Type JavaScript",
    description: "Menyimpan data dengan let, const, dan tipe data dasar.",
    category: "Pemrograman",
    content: "Variable menyimpan nilai. Gunakan const untuk nilai tetap, let untuk nilai yang bisa berubah. Hindari var (scope-nya membingungkan).\n\nTipe data primitif: string, number, boolean, null, undefined, symbol, bigint. Tipe kompleks: object, array, function. typeof digunakan untuk cek tipe.",
    examples: ["const nama = 'Budi'", "let umur = 16", "typeof umur // 'number'"],
    keyPoints: ["const = tetap, let = bisa berubah", "Ada tipe primitif & kompleks", "typeof untuk cek tipe"],
    quiz: [{ question: "Keyword untuk variable yang tidak boleh diubah adalah...", options: ["var", "let", "const", "static"], correct: 2, explanation: "const untuk konstanta." }],
  },
  {
    id: "mat-23", number: 23, title: "Operator dan Conditional",
    description: "Operasi matematika, perbandingan, dan percabangan.",
    category: "Pemrograman",
    content: "Operator: aritmatika (+ - * / %), perbandingan (== === != !== > <), logika (&& || !), assignment (= += -=).\n\nGunakan === (strict equality) daripada ==. Conditional: if/else if/else, switch, dan ternary (kondisi ? a : b). Conditional menentukan alur program berdasarkan kondisi.",
    examples: ["if (nilai >= 75) { lulus }", "x === 10", "usia >= 17 && punyaKTP"],
    keyPoints: ["=== lebih aman dari ==", "if/else untuk percabangan", "&& || ! untuk logika"],
    quiz: [{ question: "Operator perbandingan strict equality adalah...", options: ["=", "==", "===", "!="], correct: 2, explanation: "=== membandingkan nilai dan tipe." }],
  },
  {
    id: "mat-24", number: 24, title: "Function JavaScript",
    description: "Membuat blok kode yang bisa dipanggil ulang.",
    category: "Pemrograman",
    content: "Function mengelompokkan kode agar reusable. Cara deklarasi: function nama() {}, const nama = function() {}, const nama = () => {} (arrow function).\n\nFunction bisa menerima parameter dan mengembalikan nilai (return). Scope: variable di dalam function bersifat lokal. Arrow function ringkas dan sering dipakai di callback modern.",
    examples: ["function sapa(nama) { return 'Halo ' + nama }", "const tambah = (a,b) => a+b", "sapa('Ani')"],
    keyPoints: ["Function = reusable", "Parameter & return", "Arrow function modern"],
    quiz: [{ question: "Keyword untuk mengembalikan nilai dari function adalah...", options: ["yield", "return", "send", "output"], correct: 1, explanation: "return mengembalikan nilai." }],
  },
  {
    id: "mat-25", number: 25, title: "Array dan Object",
    description: "Struktur data untuk kumpulan nilai dan pasangan key-value.",
    category: "Pemrograman",
    content: "Array adalah daftar berurutan: const angka = [1,2,3]. Akses dengan index (angka[0]). Method berguna: push, pop, map, filter, forEach, find.\n\nObject menyimpan data berpasangan key-value: const siswa = { nama: 'Budi', umur: 16 }. Akses: siswa.nama atau siswa['nama']. Array of objects sangat umum untuk data list.",
    examples: ["const mapel = ['MTK','IPA']", "siswa.nama", "angka.map(x => x*2)"],
    keyPoints: ["Array = list berindex", "Object = key-value", "map/filter sangat berguna"],
    quiz: [{ question: "Untuk menambah elemen di akhir array, gunakan...", options: ["pop()", "push()", "shift()", "slice()"], correct: 1, explanation: "push() menambah di akhir." }],
  },
  {
    id: "mat-26", number: 26, title: "Dasar Database",
    description: "Konsep penyimpanan data terstruktur.",
    category: "Database",
    content: "Database adalah kumpulan data terorganisir yang mudah diakses, dikelola, dan diperbarui. DBMS (Database Management System) contohnya MySQL, PostgreSQL, MongoDB.\n\nDatabase relasional memakai tabel (baris = record, kolom = field) dan relasi antar tabel. Database non-relasional (NoSQL) lebih fleksibel untuk data semi-terstruktur.",
    examples: ["Tabel siswa: id, nama, kelas", "MySQL di server sekolah", "MongoDB untuk data JSON"],
    keyPoints: ["DBMS mengelola database", "Relasional = tabel", "NoSQL = fleksibel"],
    quiz: [{ question: "Contoh DBMS relasional adalah...", options: ["MongoDB", "Redis", "MySQL", "Neo4j"], correct: 2, explanation: "MySQL adalah RDBMS populer." }],
  },
  {
    id: "mat-27", number: 27, title: "SQL Dasar",
    description: "Bahasa query untuk mengelola database relasional.",
    category: "Database",
    content: "SQL (Structured Query Language) digunakan untuk CRUD: Create, Read, Update, Delete.\n\nPerintah dasar:\nSELECT * FROM siswa;\nINSERT INTO siswa (nama, kelas) VALUES ('Budi', 'X TKJ');\nUPDATE siswa SET kelas='XI TKJ' WHERE id=1;\nDELETE FROM siswa WHERE id=1;\n\nWHERE, ORDER BY, JOIN adalah klausa penting.",
    examples: ["SELECT nama FROM siswa WHERE kelas='X TKJ'", "ORDER BY nama ASC", "JOIN untuk gabung tabel"],
    keyPoints: ["SELECT baca data", "INSERT/UPDATE/DELETE ubah data", "WHERE untuk filter"],
    quiz: [{ question: "Perintah SQL untuk mengambil data adalah...", options: ["GET", "SELECT", "FETCH", "READ"], correct: 1, explanation: "SELECT digunakan untuk query data." }],
  },
  {
    id: "mat-28", number: 28, title: "Cyber Security Dasar",
    description: "Ancaman digital dan cara melindungi diri.",
    category: "Keamanan",
    content: "Cyber security adalah praktik melindungi sistem, jaringan, dan data dari serangan digital. Ancaman umum: malware, phishing, ransomware, brute force, social engineering.\n\nPrinsip dasar: CIA Triad — Confidentiality, Integrity, Availability. Pertahanan: update software, antivirus, firewall, backup, edukasi user. Keamanan adalah tanggung jawab bersama.",
    examples: ["Jangan klik link mencurigakan", "Aktifkan 2FA", "Backup rutin ke cloud/drive"],
    keyPoints: ["CIA: Confidentiality, Integrity, Availability", "Phishing sering menipu user", "Update & backup penting"],
    quiz: [{ question: "Usaha menipu user agar memberi password disebut...", options: ["Malware", "Phishing", "Firewall", "Encryption"], correct: 1, explanation: "Phishing menipu korban lewat pesan palsu." }],
  },
  {
    id: "mat-29", number: 29, title: "Password dan Authentication",
    description: "Membuat password kuat dan sistem autentikasi.",
    category: "Keamanan",
    content: "Password kuat: minimal 12 karakter, kombinasi huruf besar-kecil, angka, simbol, unik per akun. Jangan pakai tanggal lahir atau nama sendiri.\n\nAuthentication membuktikan identitas: sesuatu yang kamu tahu (password), punya (HP/token), atau siapa kamu (biometrik). MFA/2FA menggabungkan minimal 2 faktor — sangat disarankan.\n\nPassword manager membantu menyimpan password unik dengan aman.",
    examples: ["2FA via SMS/authenticator app", "Password manager: Bitwarden", "Hindari '123456' atau 'password'"],
    keyPoints: ["Password unik & panjang", "Aktifkan 2FA", "Jangan share password"],
    quiz: [{ question: "Autentikasi dengan dua faktor disebut...", options: ["SSO", "2FA/MFA", "VPN", "SSL"], correct: 1, explanation: "2FA/MFA = multi-factor authentication." }],
  },
  {
    id: "mat-30", number: 30, title: "Etika Digital",
    description: "Bersikap bijak dan bertanggung jawab di dunia maya.",
    category: "Keamanan",
    content: "Etika digital mencakup norma berperilaku di internet: hormati privasi orang lain, jangan sebarkan hoax, hindari cyberbullying, hargai karya orang (jangan plagiat), dan bijak dalam berkomentar.\n\nJejak digital bersifat permanen. Pikirkan sebelum post. Undang-undang ITE di Indonesia mengatur tindak pidana di ruang digital. Gunakan teknologi untuk kebaikan.",
    examples: ["Cek fakta sebelum share", "Jangan bully di komentar", "Sebut sumber saat mengutip"],
    keyPoints: ["Hormati privasi & karya orang", "Jejak digital sulit dihapus", "Gunakan teknologi secara positif"],
    quiz: [{ question: "Menyebarkan berita bohong di internet termasuk pelanggaran...", options: ["Etika digital", "Hanya opini", "Hak cipta saja", "Tidak apa-apa"], correct: 0, explanation: "Menyebarkan hoax melanggar etika digital dan bisa kena hukum." }],
  },
  {
    id: "mat-31", number: 31, title: "Algoritma dan Flowchart",
    description: "Langkah sistematis memecahkan masalah sebelum coding.",
    category: "Pemrograman",
    content: "Algoritma adalah urutan langkah logis untuk menyelesaikan masalah. Syarat: jelas, berhingga, efektif, dan ada output.\n\nFlowchart menggambarkan algoritma secara visual dengan simbol: oval (start/end), parallelogram (input/output), rectangle (proses), diamond (keputusan).\n\nPseudocode adalah algoritma dalam bentuk teks mirip kode — mudah diterjemahkan ke bahasa pemrograman.",
    examples: ["Algoritma menghitung rata-rata nilai", "Flowchart login user", "Pseudocode sorting"],
    keyPoints: ["Algoritma = langkah logis", "Flowchart = visual", "Rancang dulu sebelum coding"],
    quiz: [{ question: "Simbol diamond pada flowchart berarti...", options: ["Proses", "Keputusan/percabangan", "Input", "Mulai"], correct: 1, explanation: "Diamond = decision." }],
  },
  {
    id: "mat-32", number: 32, title: "Dasar Pemrograman",
    description: "Konsep fundamental menulis program komputer.",
    category: "Pemrograman",
    content: "Pemrograman adalah proses menulis instruksi agar komputer menyelesaikan tugas. Konsep dasar: variable, tipe data, operator, percabangan, perulangan (for, while), function, dan struktur data.\n\nBahasa populer untuk pemula: Python (sederhana), JavaScript (web), Java (OOP). Computational thinking: dekomposisi, pattern recognition, abstraksi, algoritma.\n\nDebugging adalah keterampilan penting: baca error, uji sebagian, perbaiki bertahap.",
    examples: ["for loop mencetak 1-10", "if/else menentukan kelulusan", "Function hitungLuas(p,l)"],
    keyPoints: ["Urutan, percabangan, perulangan", "Computational thinking", "Debugging wajib dikuasai"],
    quiz: [{ question: "Proses menemukan dan memperbaiki error disebut...", options: ["Compiling", "Debugging", "Deploying", "Rendering"], correct: 1, explanation: "Debugging = cari & perbaiki bug." }],
  },
  {
    id: "mat-33", number: 33, title: "Pengenalan AI dan Generative AI",
    description: "Memahami kecerdasan buatan dan AI generatif.",
    category: "AI",
    content: "Artificial Intelligence (AI) adalah kemampuan mesin meniru kecerdasan manusia: belajar, menalar, memecahkan masalah. Machine Learning adalah cabang AI yang belajar dari data.\n\nGenerative AI (ChatGPT, Gemini, image generators) menghasilkan konten baru: teks, gambar, kode, audio. AI membantu belajar, tapi jangan dipakai untuk menyontek — pahami hasilnya.\n\nEtika AI: bias, privasi, hoax yang dihasilkan AI, dan tanggung jawab pengguna. Gunakan AI sebagai asisten, bukan pengganti berpikir.",
    examples: ["ChatGPT & Gemini untuk tanya materi", "Generator gambar AI", "AI deteksi spam email"],
    keyPoints: ["AI meniru kecerdasan", "Generative AI menghasilkan konten", "Pakai bijak & etis"],
    quiz: [{ question: "AI yang dapat menghasilkan teks atau gambar baru disebut...", options: ["Reactive AI", "Generative AI", "Analytics AI", "Legacy AI"], correct: 1, explanation: "Generative AI menghasilkan konten baru." }],
  },
];

MATERIALS.push(...MORE2);

export function getMaterial(id: string) {
  return MATERIALS.find((m) => m.id === id);
}

export function getMaterialsByCategory(cat: string) {
  return MATERIALS.filter((m) => m.category === cat);
}

export const CATEGORIES_LEARN = Array.from(new Set(MATERIALS.map((m) => m.category)));
