import { NextRequest, NextResponse } from "next/server";
import { getCompetitionById, startCompetition, pauseCompetition, getLeaderboard, submitAnswer, autoTimeout, hydrateCompetition, getPlayerState, type Competition } from "@/lib/competition-store";
export const dynamic = "force-dynamic"; export const revalidate = 0;
function tryHydrate(token?: string | null) { if (!token) return; try { const data = JSON.parse(Buffer.from(token, "base64url").toString("utf8")) as Competition; if (data?.id) hydrateCompetition(data); } catch {} }
function response(comp: Competition, sessionToken?: string | null) { const player = sessionToken ? getPlayerState(comp, sessionToken) : null; return { id: comp.id, name: comp.name, status: comp.status, currentQuestionIndex: player?.player.currentQuestionIndex ?? comp.currentQuestionIndex, totalQuestions: comp.questions.length, timePerQuestion: comp.timePerQuestion, questionStartedAt: player ? comp.players.find((p) => p.sessionToken === sessionToken)?.questionStartedAt : comp.questionStartedAt, playerCount: comp.players.length, players: comp.players.map((p) => ({ id: p.id, name: p.name, score: p.score, status: p.status, currentQuestionIndex: p.currentQuestionIndex })), currentQuestion: player?.currentQuestion || null, player: player?.player || null, leaderboard: comp.status === "finished" ? getLeaderboard(comp.id) : undefined }; }
export async function GET(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; tryHydrate(request.nextUrl.searchParams.get("token") || request.nextUrl.searchParams.get("p")); const comp = getCompetitionById(id); if (!comp) return NextResponse.json({ error: "Kompetisi tidak ditemukan." }, { status: 404 }); const sessionToken = request.nextUrl.searchParams.get("sessionToken"); if (sessionToken) autoTimeout(id, sessionToken); return NextResponse.json(response(comp, sessionToken), { headers: { "Cache-Control": "no-store" } }); }
export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; const body = await request.json().catch(() => ({})); tryHydrate(body.token); const { action, teacherId, sessionToken, questionId, answerIndex } = body;
  if (action === "start") { const r = startCompetition(id, teacherId || "guruku"); return "error" in r ? NextResponse.json({ error: r.error }, { status: 400 }) : NextResponse.json({ success: true, status: r.status }); }
  if (action === "pause" || action === "resume") { const r = pauseCompetition(id, teacherId || "guruku", action === "pause"); return "error" in r ? NextResponse.json({ error: r.error }, { status: 400 }) : NextResponse.json({ success: true, status: r.status }); }
  if (action === "answer" || action === "timeout") { if (!sessionToken || !questionId || (action === "answer" && typeof answerIndex !== "number")) return NextResponse.json({ error: "Data jawaban tidak lengkap" }, { status: 400 }); const r = action === "timeout" ? autoTimeout(id, sessionToken) : submitAnswer(id, sessionToken, questionId, answerIndex); return !r ? NextResponse.json({ error: "Timer belum habis" }, { status: 409 }) : "error" in r ? NextResponse.json({ error: r.error }, { status: r.error.includes("sudah terjawab") ? 200 : 400 }) : NextResponse.json({ success: true, answered: true, ...r }, { headers: { "Cache-Control": "no-store" } }); }
  if (action === "leaderboard") { return NextResponse.json({ leaderboard: getLeaderboard(id) }, { headers: { "Cache-Control": "no-store" } }); }
  return NextResponse.json({ error: "Manual next question dinonaktifkan; soal maju otomatis setelah jawaban tersimpan." }, { status: 410 });
}
