"use client";
import { useEffect, useState } from "react";
import { Brain, Eye, EyeOff, Film, Link as LinkIcon, LogOut, Music, Save, Settings } from "lucide-react";

type ConfigForm = { geminiApiKey: string; geminiModel: string; tmdbApiKey: string; instagramUrl: string; musicUrl: string; musicEnabled: boolean };
const empty: ConfigForm = { geminiApiKey: "", geminiModel: "gemini-2.5-flash", tmdbApiKey: "", instagramUrl: "", musicUrl: "", musicEnabled: false };
export default function AdminPage() {
  const [authenticated, setAuthenticated] = useState(false); const [password, setPassword] = useState(""); const [form, setForm] = useState(empty); const [status, setStatus] = useState<any>(null); const [tab, setTab] = useState("general"); const [saving, setSaving] = useState(false); const [showGemini, setShowGemini] = useState(false); const [showTmdb, setShowTmdb] = useState(false);
  useEffect(() => { setAuthenticated(localStorage.getItem("admin_auth") === "true"); fetch("/api/config", { cache: "no-store" }).then((r) => r.json()).then((d) => setStatus(d)).catch(() => {}); }, []);
  const login = (e: React.FormEvent) => { e.preventDefault(); if (!password) return; setAuthenticated(true); localStorage.setItem("admin_auth", "true"); };
  const save = async () => { setSaving(true); setStatus(null); try { const r = await fetch("/api/config", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, adminPassword: password }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Gagal menyimpan"); setStatus({ ...d.config, success: true, verified: d.verified }); setForm((v) => ({ ...v, geminiApiKey: "", tmdbApiKey: "", geminiModel: d.config.geminiModel })); } catch (e) { setStatus({ error: e instanceof Error ? e.message : "Gagal menyimpan" }); } finally { setSaving(false); } };
  if (!authenticated) return <main className="min-h-screen grid place-items-center p-6 bg-gray-50"><form onSubmit={login} className="w-full max-w-sm bg-white rounded-2xl p-8 shadow-sm"><div className="w-12 h-12 bg-black text-white rounded-xl grid place-items-center mb-5"><Settings /></div><h1 className="text-2xl font-bold">Global Configuration</h1><p className="text-sm text-gray-500 mt-2 mb-6">Masuk untuk mengatur server dan seluruh pengguna publik.</p><input autoFocus type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password admin" className="w-full border rounded-xl px-4 py-3 mb-4" required /><button className="w-full bg-black text-white rounded-xl py-3 font-medium">Masuk</button></form></main>;
  return <main className="min-h-screen bg-gray-50 p-4 sm:p-8"><div className="max-w-4xl mx-auto"><header className="flex items-center justify-between mb-8"><div className="flex items-center gap-3"><div className="w-11 h-11 bg-black text-white rounded-xl grid place-items-center"><Settings /></div><div><h1 className="text-2xl font-bold">Global Configuration</h1><p className="text-sm text-gray-500">Satu konfigurasi server untuk AI, film, musik, dan publik</p></div></div><button onClick={() => { localStorage.removeItem("admin_auth"); setAuthenticated(false); setPassword(""); }} className="text-sm text-red-600 flex gap-2 items-center"><LogOut className="w-4 h-4" /> Keluar</button></header>
  <nav className="flex gap-2 mb-6 overflow-x-auto">{[["general", "Umum", LinkIcon], ["ai", "AI", Brain], ["film", "Film", Film], ["music", "Musik", Music]].map(([id, label, Icon]: any) => <button key={id} onClick={() => setTab(id)} className={`px-4 py-2.5 rounded-xl flex items-center gap-2 text-sm ${tab === id ? "bg-black text-white" : "bg-white text-gray-700"}`}><Icon className="w-4 h-4" />{label}</button>)}</nav>
  <section className="bg-white rounded-2xl p-6 shadow-sm space-y-5">{tab === "general" && <><h2 className="font-bold text-lg">Status sistem</h2><div className="grid sm:grid-cols-2 gap-3">{[["AI", status?.geminiConfigured], ["TMDB", status?.tmdbConfigured], ["Global Config", status?.updatedAt > 0]].map(([label, ok]: any) => <div key={label} className="border rounded-xl p-4 flex justify-between"><span>{label}</span><b className={ok ? "text-green-600" : "text-amber-600"}>{ok ? "CONNECTED" : "NOT CONFIGURED"}</b></div>)}</div><label className="block text-sm font-medium">Instagram kelas<input value={form.instagramUrl} onChange={(e) => setForm({ ...form, instagramUrl: e.target.value })} className="w-full border rounded-xl px-4 py-3 mt-2" placeholder="https://instagram.com/..." /></label></>}
  {tab === "ai" && <><h2 className="font-bold text-lg flex items-center gap-2"><Brain className="w-5 h-5" /> Google Gemini</h2><Secret label="Gemini API Key" value={form.geminiApiKey} visible={showGemini} setVisible={setShowGemini} onChange={(v: string) => setForm({ ...form, geminiApiKey: v })} placeholder="Key hanya dikirim saat verifikasi server" /><label className="block text-sm font-medium">Default model<select value={form.geminiModel} onChange={(e) => setForm({ ...form, geminiModel: e.target.value })} className="w-full border rounded-xl px-4 py-3 mt-2"><option>gemini-2.5-flash</option><option>gemini-2.5-flash-lite</option><option>gemini-2.0-flash</option><option>gemini-flash-latest</option></select></label><p className="text-xs text-gray-500">Model akan diuji ke provider sebelum konfigurasi diaktifkan.</p></>}
  {tab === "film" && <><h2 className="font-bold text-lg flex items-center gap-2"><Film className="w-5 h-5" /> TMDB</h2><Secret label="TMDB API Key" value={form.tmdbApiKey} visible={showTmdb} setVisible={setShowTmdb} onChange={(v: string) => setForm({ ...form, tmdbApiKey: v })} placeholder="Key hanya dikirim saat verifikasi server" /></>}
  {tab === "music" && <><h2 className="font-bold text-lg flex items-center gap-2"><Music className="w-5 h-5" /> Public Background Music</h2><label className="flex items-center gap-3"><input type="checkbox" checked={form.musicEnabled} onChange={(e) => setForm({ ...form, musicEnabled: e.target.checked })} /> Aktifkan musik publik</label><label className="block text-sm font-medium">URL MP3 HTTPS<input type="url" value={form.musicUrl} onChange={(e) => setForm({ ...form, musicUrl: e.target.value })} className="w-full border rounded-xl px-4 py-3 mt-2" placeholder="https://.../music.mp3" /></label><p className="text-xs text-gray-500">Autoplay tetap mengikuti kebijakan browser.</p></>}
  <div className="pt-4 border-t flex items-center justify-between gap-4"><div className="text-sm">{status?.error ? <span className="text-red-600">{status.error}</span> : status?.success ? <span className="text-green-600">Terverifikasi dan tersimpan global.</span> : <span className="text-gray-500">Secret tidak pernah dikirim ke GET/browser setelah disimpan.</span>}</div><button onClick={save} disabled={saving} className="bg-black text-white rounded-xl px-5 py-3 flex items-center gap-2 disabled:opacity-50"><Save className="w-4 h-4" />{saving ? "Memverifikasi..." : "Simpan Global"}</button></div></section></div></main>;
}
function Secret({ label, value, visible, setVisible, onChange, placeholder }: any) { return <label className="block text-sm font-medium">{label}<div className="relative mt-2"><input type={visible ? "text" : "password"} value={value} onChange={(e) => onChange(e.target.value)} className="w-full border rounded-xl px-4 py-3 pr-12 font-mono" placeholder={placeholder} /><button type="button" onClick={() => setVisible(!visible)} className="absolute right-3 top-3 text-gray-500">{visible ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}</button></div></label>; }
