"use client";
import { useState, useEffect, useCallback } from "react";
import { useParams, useRouter } from "next/navigation";
import { Loader2, CheckCircle, XCircle, Users } from "lucide-react";
export default function PlayPage() { const params = useParams(); const router = useRouter(); const id = params.code as string; const [data, setData] = useState<any>(); const [session, setSession] = useState<any>(); const [selected, setSelected] = useState<number | null>(null); const [submitting, setSubmitting] = useState(false); const [notice, setNotice] = useState<any>(null); const [timeLeft, setTimeLeft] = useState(20); const [isTeacher, setIsTeacher] = useState(false);
 const load = useCallback(async () => { const sess = session || JSON.parse(localStorage.getItem(`comp_session_${id}`) || "null"); const qs = sess?.sessionToken ? `?sessionToken=${encodeURIComponent(sess.sessionToken)}` : ""; const r = await fetch(`/api/competitions/${id}${qs}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) return; setData(d); if (d.status === "finished") router.push(`/kompetisi/${id}/result`); if (d.status === "waiting") router.push(`/kompetisi/${id}/lobby`); if (d.questionStartedAt && d.timePerQuestion) setTimeLeft(Math.max(0, d.timePerQuestion - Math.floor((Date.now() - d.questionStartedAt) / 1000))); }, [id, router, session]);
 useEffect(() => { const teacher = localStorage.getItem("teacher_token") || localStorage.getItem("admin_auth"); setIsTeacher(Boolean(teacher)); const raw = localStorage.getItem(`comp_session_${id}`); if (raw) try { setSession(JSON.parse(raw)); } catch {} }, [id]); useEffect(() => { load(); const t = setInterval(load, 1500); return () => clearInterval(t); }, [load]); useEffect(() => { setSelected(null); setNotice(null); }, [data?.player?.currentQuestionIndex]); useEffect(() => { if (timeLeft > 0) { const t = setTimeout(() => setTimeLeft((v) => v - 1), 1000); return () => clearTimeout(t); } if (timeLeft === 0 && data?.currentQuestion && session && !submitting) submit(true); }, [timeLeft]);
 const submit = async (timeout = false) => { if (!session || !data?.currentQuestion || submitting || (!timeout && selected === null)) return; setSubmitting(true); try { const r = await fetch(`/api/competitions/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: timeout ? "timeout" : "answer", sessionToken: session.sessionToken, questionId: data.currentQuestion.id, answerIndex: selected }) }); const d = await r.json(); if (r.ok) { setNotice(d); setSelected(null); await load(); } else setNotice({ error: d.error }); } finally { setSubmitting(false); } };
 if (!data) return <div className="min-h-screen grid place-items-center"><Loader2 className="animate-spin" /></div>;
 if (isTeacher) return <main className="min-h-screen p-6"><div className="max-w-2xl mx-auto"><div className="bg-black text-white rounded-2xl p-5"><p className="text-xs opacity-70">HOST MODE · AUTO-NEXT AKTIF</p><h1 className="font-bold text-xl">{data.name}</h1><p className="mt-2">Peserta: {data.playerCount} · Soal aktif tertinggi: {(data.currentQuestionIndex || 0) + 1}/{data.totalQuestions}</p></div><div className="bg-white border rounded-2xl p-5 mt-4"><div className="flex gap-2 items-center font-medium"><Users className="w-5 h-5" /> Progress peserta</div>{data.players?.map((p: any) => <div key={p.id} className="flex justify-between text-sm py-2 border-b"><span>{p.name}</span><span>Soal {Math.min(p.currentQuestionIndex + 1, data.totalQuestions)}/{data.totalQuestions} · {p.score} pts</span></div>)}</div></div></main>;
 const q = data.currentQuestion; if (!q) return <div className="min-h-screen grid place-items-center text-center p-6"><div>{data.status === "paused" ? "Kompetisi sedang dijeda oleh guru." : "Menunggu kompetisi dimulai..."}<button onClick={load} className="block mx-auto mt-4 underline">Refresh status</button></div></div>;
 return <main className="min-h-screen p-5 bg-white"><div className="max-w-lg mx-auto"><div className="flex justify-between text-sm text-gray-500 mb-4"><span>Soal {q.index + 1}/{data.totalQuestions}</span><b className={timeLeft <= 5 ? "text-red-600" : "text-black"}>{timeLeft}s</b></div><h1 className="text-xl font-bold mb-6">{q.question}</h1><div className="space-y-3">{q.options.map((o: string, i: number) => <button key={o} onClick={() => setSelected(i)} disabled={submitting} className={`w-full text-left p-4 rounded-xl border ${selected === i ? "bg-black text-white border-black" : "border-gray-200"}`}><b>{String.fromCharCode(65 + i)}.</b> {o}</button>)}</div><button onClick={() => submit()} disabled={selected === null || submitting} className="w-full mt-6 py-3 rounded-xl bg-black text-white disabled:opacity-40">{submitting ? "Menyimpan..." : "Kirim jawaban"}</button>{notice && <div className={`mt-4 p-4 rounded-xl ${notice.error ? "bg-red-50 text-red-700" : notice.correct ? "bg-green-50" : "bg-amber-50"}`}>{notice.error || (notice.finished ? "Kompetisi selesai!" : <><div className="flex gap-2 items-center font-medium"><CheckCircle className="w-5 h-5" /> Jawaban tersimpan</div><p className="text-sm mt-1">Soal berikutnya dimuat otomatis...</p></>)}</div>}</div></main>; }
