"use client";
import { useEffect, useRef, useState } from "react";
import { Volume2, VolumeX, Pause, Play } from "lucide-react";
export default function MusicPlayer() { const audioRef = useRef<HTMLAudioElement | null>(null); const [url, setUrl] = useState(""); const [playing, setPlaying] = useState(false); const [muted, setMuted] = useState(true); const [visible, setVisible] = useState(false); const [needGesture, setNeedGesture] = useState(false);
 useEffect(() => { fetch("/api/config", { cache: "no-store" }).then((r) => r.json()).then((d) => { if (d.musicEnabled && d.musicUrl) setUrl(d.musicUrl); }).catch(() => {}); try { const p = JSON.parse(localStorage.getItem("music_pref") || "{}"); if (typeof p.muted === "boolean") setMuted(p.muted); } catch {} }, []);
 useEffect(() => { if (!url) { setVisible(false); return; } setVisible(true); const audio = audioRef.current || new Audio(); audioRef.current = audio; audio.src = url; audio.loop = true; audio.preload = "auto"; audio.muted = muted; audio.play().then(() => { setPlaying(true); setNeedGesture(false); }).catch(() => { setPlaying(false); setNeedGesture(true); }); }, [url]);
 useEffect(() => { if (audioRef.current) audioRef.current.muted = muted; try { localStorage.setItem("music_pref", JSON.stringify({ muted })); } catch {} }, [muted]);
 const togglePlay = () => { const audio = audioRef.current; if (!audio) return; if (playing) { audio.pause(); setPlaying(false); } else audio.play().then(() => { setPlaying(true); setNeedGesture(false); }).catch(() => setNeedGesture(true)); }; const toggleMute = () => { setMuted((m) => !m); if (audioRef.current && !playing) audioRef.current.play().then(() => setPlaying(true)).catch(() => setNeedGesture(true)); };
 if (!visible) return null; return <div className="fixed bottom-4 right-4 z-50 flex items-center gap-2 bg-white border shadow-lg rounded-full px-3 py-2">{needGesture && <button onClick={togglePlay} className="text-xs font-medium px-2">Aktifkan Musik</button>}<button onClick={togglePlay} className="p-1.5" aria-label="Play/Pause">{playing ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4" />}</button><button onClick={toggleMute} className="p-1.5" aria-label="Mute">{muted ? <VolumeX className="w-4 h-4" /> : <Volume2 className="w-4 h-4" />}</button></div>;
}
